/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Participant } from "./Participant";
import { ParticipantCountArgs } from "./ParticipantCountArgs";
import { ParticipantFindManyArgs } from "./ParticipantFindManyArgs";
import { ParticipantFindUniqueArgs } from "./ParticipantFindUniqueArgs";
import { CreateParticipantArgs } from "./CreateParticipantArgs";
import { UpdateParticipantArgs } from "./UpdateParticipantArgs";
import { DeleteParticipantArgs } from "./DeleteParticipantArgs";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { User } from "../../user/base/User";
import { ParticipantService } from "../participant.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Participant)
export class ParticipantResolverBase {
  constructor(
    protected readonly service: ParticipantService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "read",
    possession: "any",
  })
  async _participantsMeta(
    @graphql.Args() args: ParticipantCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Participant])
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "read",
    possession: "any",
  })
  async participants(
    @graphql.Args() args: ParticipantFindManyArgs
  ): Promise<Participant[]> {
    return this.service.participants(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Participant, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "read",
    possession: "own",
  })
  async participant(
    @graphql.Args() args: ParticipantFindUniqueArgs
  ): Promise<Participant | null> {
    const result = await this.service.participant(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Participant)
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "create",
    possession: "any",
  })
  async createParticipant(
    @graphql.Args() args: CreateParticipantArgs
  ): Promise<Participant> {
    return await this.service.createParticipant({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Participant)
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "update",
    possession: "any",
  })
  async updateParticipant(
    @graphql.Args() args: UpdateParticipantArgs
  ): Promise<Participant | null> {
    try {
      return await this.service.updateParticipant({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Participant)
  @nestAccessControl.UseRoles({
    resource: "Participant",
    action: "delete",
    possession: "any",
  })
  async deleteParticipant(
    @graphql.Args() args: DeleteParticipantArgs
  ): Promise<Participant | null> {
    try {
      return await this.service.deleteParticipant(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Message], { name: "messages" })
  @nestAccessControl.UseRoles({
    resource: "Message",
    action: "read",
    possession: "any",
  })
  async findMessages(
    @graphql.Parent() parent: Participant,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessages(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Participant): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
