/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ScreenShareService } from "../screenShare.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ScreenShareCreateInput } from "./ScreenShareCreateInput";
import { ScreenShare } from "./ScreenShare";
import { ScreenShareFindManyArgs } from "./ScreenShareFindManyArgs";
import { ScreenShareWhereUniqueInput } from "./ScreenShareWhereUniqueInput";
import { ScreenShareUpdateInput } from "./ScreenShareUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ScreenShareControllerBase {
  constructor(
    protected readonly service: ScreenShareService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ScreenShare })
  @nestAccessControl.UseRoles({
    resource: "ScreenShare",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createScreenShare(
    @common.Body() data: ScreenShareCreateInput
  ): Promise<ScreenShare> {
    return await this.service.createScreenShare({
      data: data,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ScreenShare] })
  @ApiNestedQuery(ScreenShareFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ScreenShare",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async screenShares(@common.Req() request: Request): Promise<ScreenShare[]> {
    const args = plainToClass(ScreenShareFindManyArgs, request.query);
    return this.service.screenShares({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ScreenShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScreenShare",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async screenShare(
    @common.Param() params: ScreenShareWhereUniqueInput
  ): Promise<ScreenShare | null> {
    const result = await this.service.screenShare({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isActive: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ScreenShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScreenShare",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateScreenShare(
    @common.Param() params: ScreenShareWhereUniqueInput,
    @common.Body() data: ScreenShareUpdateInput
  ): Promise<ScreenShare | null> {
    try {
      return await this.service.updateScreenShare({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          isActive: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ScreenShare })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ScreenShare",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteScreenShare(
    @common.Param() params: ScreenShareWhereUniqueInput
  ): Promise<ScreenShare | null> {
    try {
      return await this.service.deleteScreenShare({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isActive: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
